version: "3"
services:

  inventboost_db:
    container_name: inventboost_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/inventboost_db:/data/postgres

    environment:
      POSTGRES_DB: inventboost
      POSTGRES_USER: inventboost
      POSTGRES_PASSWORD: inventboost

    networks:
      - postgres

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - postgres
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      - MINIO_DEFAULT_BUCKETS=inventboost

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379

  pgadmin:
    links:
      - inventboost_db:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:8.6
    ports:
      - "8056:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  minio_data:
    driver: local
